App/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = "App"

urlpatterns = [
    path('', views.index, name='Accueil'),
    path('upload_factures/', views.upload_factures, name='upload_factures'),
    path('import_auto/', views.lancer_import_auto, name='import_auto'),
    path('upload_catalogue_excel/', views.upload_catalogue_excel, name='upload_catalogue_excel'),
    path('tableau_synthese/', views.tableau_synthese, name='tableau_synthese'),
    path('tableau_grossiste/', views.tableau_grossiste, name='tableau_grossiste'),
    path('tableau_simplifie/', views.tableau_simplifie, name='tableau_simplifie'),
    path('tableau_huitaine_cerp/', views.tableau_huitaine_cerp, name='tableau_huitaine_cerp'),
    path('telecharger_produits_tableau_simplifie/', views.telecharger_produits_tableau_simplifie, name='telecharger_produits_tableau_simplifie'),
    path('tableau_generiques/', views.tableau_generiques, name='tableau_generiques'),
    path('tableau_teva/', views.tableau_teva, name='tableau_teva'),
    path('tableau_eg/', views.tableau_eg, name='tableau_eg'),
    path('tableau_alliance/', views.tableau_alliance, name='tableau_alliance'),
    path('telecharger_releves_alliance/', views.telecharger_releves_alliance, name='telecharger_releves_alliance'),
    path('telecharger_achats/', views.telecharger_achats, name='telecharger_achats'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

AppMichelet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App.urls', namespace='App'))
]

App/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Application contrôle remises - Pharmacie Michelet</title>
</head>
<body>   
    {% include 'navbar.html' %}

    <div class="content">

        <h1>Importer des Factures</h1>

        <form method="post" enctype="multipart/form-data" action="/upload_factures/">
            {% csrf_token %}
            <input type="file" name="factures" multiple required>
            <button type="submit">Ajouter des factures</button>
        </form>

        <div class="events-box">
            <h4>Évènements d'importation</h4>
            <div class="events-content">
                <table border="0">
                    {% for ligne in events %}
                        <tr>
                            <td>{{ ligne }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>

        <div class="debug-line" onclick="toggleDebug()">
            <p>Cliquez pour afficher le débogage</p>
        </div>
    
        <div class="debug-content" id="debugContent">
            
            <!--
            <form method="post" enctype="multipart/form-data" action="/import_auto/">
                {% csrf_token %}
                <button type="submit">TEST</button>
            </form>
            -->

            {% if table_achats_finale %}
                <h2>Tableau final :</h2>
                <table border="2">
                    <tr>
                        <td>Produit</td>
                        <td>Désignation</td>
                        <td>Nb boites</td>
                        <td>Prix unitaire HT</td>
                        <td>Remise %</td>
                        <td>Remise unitaire HT</td>
                        <td>Montant HT hors remise</td>
                        <td>Montant HT</td>
                        <td>TVA</td>
                        <td>Date</td>
                        <td>Fichier de provenance</td>
                        <td>Numéro de facture</td>
                        <td>Fournisseur</td>
                    </tr>
                    {% for ligne in table_achats_finale %}
                        <tr>
                            {% for cellule in ligne %}
                                <td>{{ cellule }}</td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </table>
            {% endif %}

            {% if table_produits %}
                <h2>Tableau produits uniques :</h2>
                <table border="2">
                    <tr>
                        <td>Produit</td>
                        <td>Désignation</td>
                        <td>Prix unitaire HT</td>
                        <td>Remise %</td>
                        <td>Fournisseur</td>
                    </tr>
                    {% for ligne in table_produits %}
                        <tr>
                            {% for cellule in ligne %}
                                <td>{{ cellule }}</td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </table>
            {% endif %}

            {% if texte_page %}
                <h2>Texte page :</h2>
                <table border="2">
                    {% for ligne in texte_page %}
                        <tr>
                            <td>{{ ligne }}</td>
                        </tr>
                    {% endfor %}
                </table>
            {% endif %}

            {% if tables_page %}
                <h2>Tables page :</h2>
                <table border="2">
                    {% for ligne in tables_page %}
                        <tr>
                            <td>{{ ligne }}</td>
                        </tr>
                    {% endfor %}
                </table>
            {% endif %}
        </div>
    </div>

</body>

<script>
    function toggleDebug() {
        var debugContent = document.getElementById("debugContent");
        debugContent.classList.toggle("show-debug");
    }
</script>

</html>

App/templates/index_dropzone.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.9.2/min/dropzone.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.9.2/min/dropzone.min.css">
    <title>Application contrôle remises - Pharmacie Michelet</title>
</head>
<body>

    <div class="navbar">
        <a href="\">Importer des factures</a>
        <a href="#">Tableau Synthèse</a>
        <a href="\upload_catalogue_excel\">Importer un catalogue produit</a>
    </div>

    <div class="content">

        <h1>Importer des Factures</h1>

        <form action="/upload_factures/" method="post" class="dropzone" id="myDropzone">
            {% csrf_token %}
            <div class="fallback">
                <input type="file" name="factures" accept=".pdf" multiple required>
            </div>
            <button type="submit">Traiter les factures importées</button>
        </form>

        <div class="events-box">
            <h4>Évènements d'importation</h4>
            <div class="events-content">
                <table border="0">
                    {% for ligne in events %}
                        <tr>
                            <td>{{ ligne }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>

        <div class="debug-line" onclick="toggleDebug()">
            <p>Cliquez pour afficher le débogage</p>
        </div>
    
        <div class="debug-content" id="debugContent">
            {% if table_achats_finale %}
                <h2>Tableau final :</h2>
                <table border="2">
                    <tr>
                        <td>Produit</td>
                        <td>Désignation</td>
                        <td>Nb boites</td>
                        <td>Prix unitaire HT</td>
                        <td>Remise %</td>
                        <td>Remise unitaire HT</td>
                        <td>Montant HT hors remise</td>
                        <td>Montant HT</td>
                        <td>TVA</td>
                        <td>Date</td>
                        <td>Fichier de provenance</td>
                        <td>Numéro de facture</td>
                        <td>Fournisseur</td>
                    </tr>
                    {% for ligne in table_achats_finale %}
                        <tr>
                            {% for cellule in ligne %}
                                <td>{{ cellule }}</td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </table>
            {% endif %}

            {% if table_produits %}
                <h2>Tableau produits uniques :</h2>
                <table border="2">
                    <tr>
                        <td>Produit</td>
                        <td>Désignation</td>
                        <td>Prix unitaire HT</td>
                        <td>Remise %</td>
                        <td>Fournisseur</td>
                    </tr>
                    {% for ligne in table_produits %}
                        <tr>
                            {% for cellule in ligne %}
                                <td>{{ cellule }}</td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </table>
            {% endif %}

            {% if texte_page %}
                <h2>Texte page :</h2>
                <table border="2">
                    {% for ligne in texte_page %}
                        <tr>
                            <td>{{ ligne }}</td>
                        </tr>
                    {% endfor %}
                </table>
            {% endif %}

            {% if tables_page %}
                <h2>Tables page :</h2>
                <table border="2">
                    {% for ligne in tables_page %}
                        <tr>
                            <td>{{ ligne }}</td>
                        </tr>
                    {% endfor %}
                </table>
            {% endif %}
        </div>
    </div>

</body>

<script>
    function toggleDebug() {
        var debugContent = document.getElementById("debugContent");
        debugContent.classList.toggle("show-debug");
    }

    Dropzone.autoDiscover = false;

    var myDropzone = new Dropzone("#myDropzone", {
        paramName: "factures", // Nom du paramètre qui sera envoyé au serveur
        autoProcessQueue: false,
        uploadMultiple: false,    // Désactive l'envoi multiple
        parallelUploads: 1, 
        maxFilesize: 10, // Taille maximale du fichier en Mo
        acceptedFiles: ".pdf", // Types de fichiers acceptés
        addRemoveLinks: true, // Affiche les liens de suppression
        dictDefaultMessage: "Glissez-déposez les fichiers ici ou cliquez pour sélectionner",
        dictRemoveFile: "Supprimer le fichier"
    });

    document.querySelector("button[type='submit']").addEventListener("click", function() {
        myDropzone.processQueue();  // Déclenche le téléchargement des fichiers
    });

    // Event handler pour l'événement de succès d'upload
    myDropzone.on("success", function(file, response) {
        var eventsContent = document.getElementById('events-content');
        var newEvent = document.createElement('p');
        newEvent.textContent = response.events;
        eventsContent.appendChild(newEvent);

        // Mettez à jour le contenu de débogage
        var debugContent = document.getElementById('debugContent');

        console.log("Traitement terminé");
    });
</script>

</html>

App/templates/index_tableau.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_tableau.css' %}">
    <title>Application contrôle remises - Pharmacie Michelet</title>
</head>
<body>
    {% include 'navbar.html' %}

    <div class="content">
        <h1>Tableau synthèse</h1>

        <h5>
            Dernier import CERP SAE : {{ dernier_import_cerp }} <br>
            Dernier import Digipharmacie : {{ dernier_import_digi }}
        </h5>

        <form method="post" action="\tableau_synthese\">
            {% csrf_token %}
            <button type="submit">Afficher le tableau</button>
        </form>

        {% if tableau_synthese_assiette_globale %}

            <h6>Montants HT = montants avant remise, avoirs déduits<br>
                Remise assiette globale théorique = Assiette globale -9% x 2,5%<br>
                Remise assiette globale obtenue 2,5% = ligne spécialités pharmaceutiques des avoirs de remises<br>
                Avantage commercial = Assiette globale -9% x (3,8% - 2,5%)<br>
                Différences de remises = remise obtenue - remise théorique<br>
                Sous total remise grossiste théorique = somme (assiette globale + LPP + parapharmacie) x 3,8% théorique (inclut avantage commercial)<br>
                Sous total remise grossiste obtenue = somme (assiette globale + LPP + parapharmacie) x 3,8% obtenue (inclut avantage commercial)<br>
                Différence sous total remise grossiste = sous total remise grossiste obtenue - sous total remise grossiste théorique<br>
                Total remise grossiste théorique = Assiette globale -9% x 2,5% + Parapharmacie x 3,8% + LPP x 3,8% + Nb boites >450€ x 15€ + Avantage commercial<br>
                Total remise grossiste obtenue = somme des remises obtenues : remise spécialités pharmaceutiques (assiette globale) + remise LPP + remise parapharmacie + avantage commercial + remise >450€<br>
            </h6>

            <div class="column-controls" id="column-controls">
                {% for categorie in categories_assiette_globale %}
                    <div class="checkbox-container">
                        <label><input type="checkbox" class="column-toggle" data-column-index="{{ forloop.counter0 }}" checked>{{ categorie }}</label>
                    </div>
                {% endfor %}
            </div>

            <div class="column-controls-buttons">
                <button onclick="checkAll()">Tout cocher</button>
                <button onclick="uncheckAll()">Tout décocher</button>
            </div>

            <table border="1">
                <thead>
                    <tr>
                        {% for categorie in categories_assiette_globale %}
                            <th class="table-header">{{ categorie }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                {% for ligne in tableau_synthese_assiette_globale %}
                    <tr {% if ligne.0|slice:":5" == 'TOTAL' or not ligne.0 %} class="totaux" {% endif %}
                        {% if "Mois/Année" in ligne.0 %} class="inner-header" {% endif %}>
                        {% for cellule in ligne %}
                            <td>
                                {{ cellule }}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}

        {% if tableau_synthese_autres %}
        
            <br>
            <hr>
            <br>

            <h3>Autres catégories</h3>

            <h6>Remises obtenues = remises récupérées sur les factures<br>
            </h6>

            <table border="1">
                <thead>
                <tr>
                    {% for categorie in categories_autres %}
                        <th class="table-header">{{ categorie }}</th>
                    {% endfor %}
                </tr>
                </thead>
                <tbody>
                {% for ligne in tableau_synthese_autres %}
                    <tr {% if ligne.0|slice:":5" == 'TOTAL' or not ligne.0 %} class="totaux" {% endif %}
                        {% if "Mois/Année" in ligne.0 %} class="inner-header" {% endif %}>
                        {% for cellule in ligne %}
                            <td>
                                {{ cellule }}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}

    </div>

    <script>
        // JavaScript pour gérer le masquage des colonnes
        document.addEventListener("DOMContentLoaded", function() {
            // Récupérer tous les éléments de case à cocher avec la classe "column-toggle"
            var columnToggles = document.querySelectorAll(".column-toggle");

            // Ajouter des écouteurs d'événements à chaque case à cocher
            columnToggles.forEach(function(toggle) {
                toggle.addEventListener("change", function() {
                    // Récupérer l'index de la colonne à masquer ou à afficher
                    var columnIndex = parseInt(toggle.getAttribute("data-column-index"));

                    // Sélectionner toutes les cellules de la colonne avec l'index donné
                    var headerCells = document.querySelectorAll("table th:nth-child(" + (columnIndex + 1) + ")");
                    var cells = document.querySelectorAll("table tr td:nth-child(" + (columnIndex + 1) + ")");

                    // Changer la visibilité des cellules en fonction de l'état de la case à cocher
                    headerCells.forEach(function(headerCell) {
                        if (toggle.checked) {
                            headerCell.classList.remove("hidden-column");
                        } else {
                            headerCell.classList.add("hidden-column");
                        }
                    });

                    cells.forEach(function(cell) {
                        if (toggle.checked) {
                            cell.classList.remove("hidden-column");
                        } else {
                            cell.classList.add("hidden-column");
                        }
                    });
                });
            });
        });

        function checkAll() {
            document.querySelectorAll(".column-toggle").forEach(function(toggle) {
                toggle.checked = true;
                toggle.dispatchEvent(new Event('change'));
            });
        }

        function uncheckAll() {
            document.querySelectorAll(".column-toggle").forEach(function(toggle) {
                if (parseInt(toggle.getAttribute("data-column-index")) !== 0) {
                    toggle.checked = false;
                    toggle.dispatchEvent(new Event('change'));
                }
            });
        }
    </script>
</body>
</html>

App/templates/index_tableau_alliance.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_tableau.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>Application contrôle remises - Pharmacie Michelet</title>
</head>
<body>
    {% include 'navbar.html' %}

    <div class="content">
        <h1>Tableau ALLIANCE</h1>

        <h5>
            Dernier import Digipharmacie : {{ dernier_import_digi }}
        </h5>
        <form method="get" action="\tableau_alliance\" id="filter-form">
            <label for="decades">Afficher les décades:</label>
            <input type="checkbox" name="decades" id="decades" {% if show_decades %}checked{% endif %}>
            <input type="hidden" name="decades_value" id="decades_value" value="{{ show_decades|yesno:'on,off' }}">
            <br><br>
            <label for="annee">Sélectionnez une année :</label>
            <select name="annee" id="annee">
                {% for an in annees %}
                    <option value="{{ an }}" {% if an == annee_selectionnee %}selected{% endif %}>{{ an }}</option>
                {% endfor %}
            </select>
            <br><br>
            <label for="mois">Sélectionnez un mois :</label>
            <select name="mois" id="mois">
                {% for mo in mois %}
                    <option value="{{ mo }}" {% if mo == mois_selectionne %}selected{% endif %}>{{ mo }}</option>
                {% endfor %}
            </select>
        </form>

        {% if tableau_alliance %}

            <h6>
            </h6>
            
            <table id='tableau_alliance' border="1">
                <thead>
                <tr>
                    {% for categorie in colonnes %}
                        <th class="table-header">{{ categorie }}</th>
                    {% endfor %}
                </tr>
                </thead>
                <tbody>
                {% for ligne in tableau_alliance %}
                    <tr {% if ligne.0|slice:":5" == 'TOTAL' or not ligne.0 %} class="totaux" {% endif %}
                        {% if ligne.0|slice:":1" == '=' %} class="total-month" {% endif %}
                        {% if "Mois/Année" in ligne.0 %} class="inner-header" {% endif %}>
                        {% for cellule in ligne %}
                            <td>
                                {{ cellule }}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}

        <br>
        
        <form method="get" action="\telecharger_releves_alliance\">
            <button type="submit">Télécharger la liste des relevés disponibles</button>
        </form>

        <br><br>
    </div>

    <script>
        document.getElementById('decades').addEventListener('change', function() {
            // Met à jour la valeur du champ caché avant de soumettre le formulaire
            document.getElementById('decades_value').value = this.checked ? 'on' : 'off';
            document.getElementById('filter-form').submit();
        });
        document.getElementById('mois').addEventListener('change', function() {
            // Met à jour la valeur du champ caché avant de soumettre le formulaire
            document.getElementById('filter-form').submit();
        });
        document.getElementById('annee').addEventListener('change', function() {
            // Met à jour la valeur du champ caché avant de soumettre le formulaire
            document.getElementById('filter-form').submit();
        });
    </script>
</body>
</html>

App/templates/index_tableau_eg.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_tableau.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>Application contrôle remises - Pharmacie Michelet</title>
</head>
<body>
    {% include 'navbar.html' %}

    <div class="content">
        <h1>Tableau EG</h1>

        <h5>
            Dernier import CERP SAE : {{ dernier_import_cerp }} <br>
            Dernier import Digipharmacie : {{ dernier_import_digi }}
        </h5>

        <form method="post" action="\tableau_eg\">
            {% csrf_token %}
            <button type="submit">Afficher le tableau</button>
        </form>

        {% if tableau_eg %}

            <h6>Théorique = calculé à partir des % de remises du catalogue.<br>
                Obtenu = calculé à partir des % de remises effectuées sur facture.<br>
                Pour le moment, pas d'informations sur les rattrapages ou remises supplémentaires obtenus sur avoirs exceptionnels.
            </h6>
            
            <table id='tableau_eg' border="1">
                <thead>
                <tr>
                    {% for categorie in colonnes %}
                        <th class="table-header">{{ categorie }}</th>
                    {% endfor %}
                </tr>
                </thead>
                <tbody>
                {% for ligne in tableau_eg %}
                    <tr {% if ligne.0|slice:":5" == 'TOTAL' or not ligne.0 %} class="totaux" {% endif %}
                        {% if "Mois/Année" in ligne.0 %} class="inner-header" {% endif %}>
                        {% for cellule in ligne %}
                            <td>
                                {{ cellule }}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}

        <br><br>
    </div>

    <script>
        $(document).ready(function() {
            // Remplacez les titres de colonnes que vous souhaitez mettre en gras dans cette liste.
            var columnsToBold = ["GROSSISTE TOTAL HT", "DIFFERENCE REMISE GROSSISTE", "DIRECT TOTAL HT", "DIFFERENCE REMISE DIRECT", "RATTRAPAGE THEORIQUE", "RATTRAPAGE OBTENU"];
            
            // Parcourez la liste des titres de colonnes et mettez en gras chaque colonne correspondante.
            $.each(columnsToBold, function(index, columnTitle) {
                var columnIndex = $("#tableau_eg thead th").filter(function() {
                    return $(this).text() === columnTitle;
                }).index();
    
                // Si l'index est trouvé, ajoutez la classe CSS pour mettre en gras cette colonne.
                if (columnIndex >= 0) {
                    $("#tableau_teva tbody tr").each(function() {
                        $(this).find("td:eq(" + columnIndex + ")").css("font-weight", "bold");
                    });
                }
            });
        });
    </script>
</body>
</html>

App/templates/index_tableau_grossiste.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_tableau.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>Application contrôle remises - Pharmacie Michelet</title>
</head>
<body>
    <div class="navbar">
        <a href="\">Importer des factures</a>
        <a href="\tableau_synthese\">Tableau Synthèse</a>
        <a href="\tableau_grossiste\">Tableau Grossiste</a>
        <a href="\tableau_simplifie\">Tableau Simplifié</a>
        <a href="\tableau_generiques\">Tableau Génériques</a>
        <a href="\tableau_teva\">Tableau TEVA</a>
        <a href="\upload_catalogue_excel\">Importer un catalogue produit</a>
        <a href="\telecharger_achats\">Télécharger une liste d'achats</a>

        {% if user.is_authenticated %}
            <a href="{% url 'App:logout' %}?next={{ request.path }}">Se déconnecter</a>
        {% endif %}
    </div>

    <div class="content">
        <h1>Tableau grossiste</h1>

        <h5>
            Dernier import CERP SAE : {{ dernier_import_cerp }} <br>
            Dernier import Digipharmacie : {{ dernier_import_digi }}
        </h5>

        <form method="get" action="\tableau_grossiste\">
            <label for="annee">Sélectionnez une année :</label>
            <select name="annee" id="annee">
                {% for an in annees %}
                    <option value="{{ an }}" {% if an == annee_selectionnee %}selected{% endif %}>{{ an }}</option>
                {% endfor %}
            </select>
            <input type="submit" value="Filtrer">
        </form>

        {% if tableau_grossiste %}

            <table id='tableau_grossiste' border="1">
                <thead>
                <tr>
                    {% for categorie in colonnes %}
                        <th class="table-header">{{ categorie }}</th>
                    {% endfor %}
                </tr>
                </thead>
                <tbody>
                {% for ligne in tableau_grossiste %}
                    <tr {% if ligne.0|slice:":5" == 'TOTAL' or ligne.0|slice:":10" == 'DIFFERENCE' or not ligne.0 %} class="totaux" {% endif %}
                        {% if "Mois/Année" in ligne.0 %} class="inner-header" {% endif %}>
                        {% for cellule in ligne %}
                            <td>
                                {{ cellule }}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}

    </div>
</body>
</html>

App/templates/navbar.html
<nav>
    <ul class="navbar">
        <li class="nav-item">
            <a href="\tableau_synthese\">Tableau Synthèse</a>
        </li>
        <li class="nav-item dropdown">
            <a>CERP</a>
            <ul class="dropdown-menu">
                <li><a href="\tableau_grossiste\">Tableau Grossiste CERP</a></li>
                <li><a href="\tableau_simplifie\">Tableau Simplifié CERP</a></li>
                <li><a href="\tableau_huitaine_cerp\">Tableau Huitaine CERP</a></li>
            </ul>
        </li>
        <li class="nav-item dropdown">
            <a>ALLIANCE</a>
            <ul class="dropdown-menu">
                <li><a href="\tableau_alliance\">Tableau Alliance</a></li>
            </ul>
        </li>
        <li class="nav-item dropdown">
            <a>GÉNÉRIQUEURS</a>
            <ul class="dropdown-menu">
                <li><a href="\tableau_generiques\">Tableau Génériques</a></li>
                <li><a href="\tableau_teva\">Tableau TEVA</a></li>
                <li><a href="\tableau_eg\">Tableau EG</a></li>
            </ul>
        </li>
        <li class="nav-item dropdown">
            <a>Gestion</a>
            <ul class="dropdown-menu">
                <li><a href="\">Importer des factures</a></li>
                <li><a href="\upload_catalogue_excel\">Importer un catalogue produit</a></li>
                <li><a href="\telecharger_achats\">Télécharger une liste d'achats</a></li>
            </ul>
        </li>

        {% if user.is_authenticated %}
            <li class="nav-item logout">
                <a href="{% url 'App:logout' %}?next={{ request.path }}">Se déconnecter</a>
            </li>
        {% endif %}
    </ul>
</nav>